# Generated by Django 5.0.3 on 2024-09-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros_diarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(auto_now_add=True)),
                ('salinidad', models.FloatField()),
                ('nitrato', models.FloatField()),
                ('fosfato', models.FloatField()),
                ('nitrito', models.FloatField()),
                ('amonio', models.FloatField()),
                ('kh', models.FloatField()),
                ('calcio', models.IntegerField()),
                ('magnesio', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
